/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppendixRouteImport } from './routes/appendix'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiApiIdRouteImport } from './routes/api/$apiId'
import { Route as ApiApiIdIndexRouteImport } from './routes/api/$apiId.index'
import { Route as ApiApiIdExampleIdRouteImport } from './routes/api/$apiId.$exampleId'

const AppendixRoute = AppendixRouteImport.update({
  id: '/appendix',
  path: '/appendix',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiIdRoute = ApiApiIdRouteImport.update({
  id: '/api/$apiId',
  path: '/api/$apiId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiIdIndexRoute = ApiApiIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiApiIdRoute,
} as any)
const ApiApiIdExampleIdRoute = ApiApiIdExampleIdRouteImport.update({
  id: '/$exampleId',
  path: '/$exampleId',
  getParentRoute: () => ApiApiIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appendix': typeof AppendixRoute
  '/api/$apiId': typeof ApiApiIdRouteWithChildren
  '/api/$apiId/$exampleId': typeof ApiApiIdExampleIdRoute
  '/api/$apiId/': typeof ApiApiIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appendix': typeof AppendixRoute
  '/api/$apiId/$exampleId': typeof ApiApiIdExampleIdRoute
  '/api/$apiId': typeof ApiApiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appendix': typeof AppendixRoute
  '/api/$apiId': typeof ApiApiIdRouteWithChildren
  '/api/$apiId/$exampleId': typeof ApiApiIdExampleIdRoute
  '/api/$apiId/': typeof ApiApiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appendix'
    | '/api/$apiId'
    | '/api/$apiId/$exampleId'
    | '/api/$apiId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appendix' | '/api/$apiId/$exampleId' | '/api/$apiId'
  id:
    | '__root__'
    | '/'
    | '/appendix'
    | '/api/$apiId'
    | '/api/$apiId/$exampleId'
    | '/api/$apiId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppendixRoute: typeof AppendixRoute
  ApiApiIdRoute: typeof ApiApiIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/appendix': {
      id: '/appendix'
      path: '/appendix'
      fullPath: '/appendix'
      preLoaderRoute: typeof AppendixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$apiId': {
      id: '/api/$apiId'
      path: '/api/$apiId'
      fullPath: '/api/$apiId'
      preLoaderRoute: typeof ApiApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$apiId/': {
      id: '/api/$apiId/'
      path: '/'
      fullPath: '/api/$apiId/'
      preLoaderRoute: typeof ApiApiIdIndexRouteImport
      parentRoute: typeof ApiApiIdRoute
    }
    '/api/$apiId/$exampleId': {
      id: '/api/$apiId/$exampleId'
      path: '/$exampleId'
      fullPath: '/api/$apiId/$exampleId'
      preLoaderRoute: typeof ApiApiIdExampleIdRouteImport
      parentRoute: typeof ApiApiIdRoute
    }
  }
}

interface ApiApiIdRouteChildren {
  ApiApiIdExampleIdRoute: typeof ApiApiIdExampleIdRoute
  ApiApiIdIndexRoute: typeof ApiApiIdIndexRoute
}

const ApiApiIdRouteChildren: ApiApiIdRouteChildren = {
  ApiApiIdExampleIdRoute: ApiApiIdExampleIdRoute,
  ApiApiIdIndexRoute: ApiApiIdIndexRoute,
}

const ApiApiIdRouteWithChildren = ApiApiIdRoute._addFileChildren(
  ApiApiIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppendixRoute: AppendixRoute,
  ApiApiIdRoute: ApiApiIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
